# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayerKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Spotify-iOS-SDK'
  pod 'Cider', git: 'https://github.com/asklausen/Cider'
  pod "ReactiveSwift"
  pod "SwiftyJSON"
  pod "Alamofire"
  pod "SDWebImage"

end
